### ISSUE TITLE
CRUD Nedir? Ne İşe Yarar?

### ISSUE THREAD

**Issue by llnallna** [Hypance/HypanceFrontend#32]
- create
- read
- update
- delete
fonksiyonlarının araştırılması

**Comment by BerkTenk** [comment]
Araştırma için kullandığım kaynaklar:
CRUD nedir ? : https://ceaksan.com/tr/crud-create-read-update-delete , https://www.argenova.com.tr/crud-nedir
CRUD nedir?(video anlatım) : https://youtu.be/iNkspbIfcic
Uygulamalı anlatım videosu : https://youtu.be/re3OIOr9dJI
Fonksiyonların react ile kullanılması : https://www.freecodecamp.org/news/how-to-perform-crud-operations-using-react/
CRUD İşlemleri – Programlamada Crud Tanımı : https://www.freecodecamp.org/news/crud-operations-crud-definition-in-programming/
