### ISSUE TITLE
creating SummaryBox Component

### ISSUE THREAD

**Issue by llnallna** [Hypance/HypanceFrontend#8]
Creating the Component 3
-------
**Research Subject:**  What is component? Why do we use it? How do we create a component in React?
**Component Name:** SummaryBox
**Height:** Automatic

 **Please open a new branch to push your task with your Component's name as SummaryBox**

![Image](https://user-images.githubusercontent.com/75864563/193644645-6d048987-cf1e-4c77-b171-93b564a54e98.png)

**Comment by ezgikarali4** [comment]
- [ ] Bootstrap ile yapılacak.
